apiVersion: v1
kind: Service
metadata:
  labels:
    app: sequels-2
  name: sequels-2
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sequels-2
  type: NodePort
