apiVersion: v1
kind: Service
metadata:
  labels:
    app: cow-say-what
  name: cow-say-what
spec:
  ports:
  - port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: cow-say-what
  type: NodePort
