apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shurdles-2
    tier: challenge
  name: shurdles-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shurdles-2
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: shurdles-2
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/shurdles-2:20220602-101222-mod
        name: shurdles-2
        ports:
        - containerPort: 1337
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_PTRACE
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
