apiVersion: v1
kind: Service
metadata:
  labels:
    app: shurdles-2
  name: shurdles-2
spec:
  loadBalancerIP: 34.145.110.214
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: shurdles-2
  type: LoadBalancer
