apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: refreshing
    tier: challenge
  name: refreshing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: refreshing
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        app: refreshing
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
        - image: gcr.io/bsides-sf-ctf-2022/refreshing-waf:latest
          name: waf
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
        - image: gcr.io/bsides-sf-ctf-2022/refreshing-app:latest
          name: app
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
      enableServiceLinks: false
      volumes: []
