apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trivia-star
    tier: challenge
  name: trivia-star
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivia-star
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: trivia-star
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/trivia-star:20220515-162250
        name: trivia-star
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
