apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivia-star
  name: trivia-star
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: trivia-star
  type: NodePort
