apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwncap2
    tier: challenge
  name: pwncap2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwncap2
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: pwncap2
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/pwncap2:20220514-223029
        name: pwncap2
        ports:
        - containerPort: 5555
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_PTRACE
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
