apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tutorial64
    tier: challenge
  name: tutorial64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial64
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: tutorial64
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/tutorial64:20220531-094339-mod
        name: tutorial64
        ports:
        - containerPort: 6464
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
