apiVersion: v1
kind: Service
metadata:
  labels:
    app: tutorial64
  name: tutorial64
spec:
  loadBalancerIP: 34.168.110.206
  ports:
  - port: 6464
    protocol: TCP
    targetPort: 6464
  selector:
    app: tutorial64
  type: LoadBalancer
