apiVersion: v1
kind: Service
metadata:
  labels:
    app: todolist-support
  name: todolist-support
spec:
  ports:
  - port: 3124
    protocol: TCP
    targetPort: 3124
  selector:
    app: todolist-support
  type: NodePort
