apiVersion: v1
kind: Service
metadata:
  labels:
    app: reallyprettymundane
  name: reallyprettymundane
spec:
  ports:
  - port: 8371
    protocol: TCP
    targetPort: 8371
  selector:
    app: reallyprettymundane
  type: NodePort
