apiVersion: v1
kind: Service
metadata:
  labels:
    app: tutorial
  name: tutorial
spec:
  loadBalancerIP: 34.82.56.252
  ports:
  - port: 3232
    protocol: TCP
    targetPort: 3232
  selector:
    app: tutorial
  type: LoadBalancer
