apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibabit
    tier: challenge
  name: fibabit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibabit
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: fibabit
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/fibabit:20220515-145053
        name: fibabit
        ports:
        - containerPort: 5555
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
