apiVersion: v1
kind: Service
metadata:
  labels:
    app: fibabit
  name: fibabit
spec:
  loadBalancerIP: 35.185.239.96
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: fibabit
  type: LoadBalancer
