apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login4shell
    tier: challenge
  name: login4shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login4shell
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: login4shell
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/login4shell:20220531-000407-mod
        name: login4shell
        ports:
        - containerPort: 8123
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
