apiVersion: v1
kind: Service
metadata:
  labels:
    app: login4shell
  name: login4shell
spec:
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: login4shell
  type: NodePort
