apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mod-ctfauth
    tier: challenge
  name: mod-ctfauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mod-ctfauth
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: mod-ctfauth
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/mod-ctfauth:20220531-130014
        name: mod-ctfauth
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
