apiVersion: v1
kind: Service
metadata:
  labels:
    app: mod-ctfauth
  name: mod-ctfauth
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mod-ctfauth
  type: NodePort
