apiVersion: v1
kind: Service
metadata:
  labels:
    app: arboretum
  name: arboretum
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: arboretum
  type: NodePort
