apiVersion: v1
kind: Service
metadata:
  labels:
    app: sequels-1
  name: sequels-1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sequels-1
  type: NodePort
