apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: farmer-town
    tier: challenge
  name: farmer-town
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmer-town
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: farmer-town
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/farmer-town:20220515-170921
        name: farmer-town
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
