apiVersion: v1
kind: Service
metadata:
  labels:
    app: farmer-town
  name: farmer-town
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: farmer-town
  type: NodePort
