apiVersion: v1
kind: Service
metadata:
  labels:
    app: sequels-3
  name: sequels-3
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sequels-3
  type: NodePort
