apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-tutorial-1
  name: web-tutorial-1
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web-tutorial-1
  type: NodePort
