apiVersion: v1
kind: Service
metadata:
  labels:
    app: bridgekeeper
  name: bridgekeeper
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bridgekeeper
  type: NodePort
