apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: not-for-taking
    tier: challenge
  name: not-for-taking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: not-for-taking
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: not-for-taking
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/not-for-taking:20220515-213055
        name: not-for-taking
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
