apiVersion: v1
kind: Service
metadata:
  labels:
    app: not-for-taking
  name: not-for-taking
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: not-for-taking
  type: NodePort
