apiVersion: v1
kind: Service
metadata:
  labels:
    app: eip
  name: eip
spec:
  loadBalancerIP: 104.198.14.183
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: eip
  type: LoadBalancer
