apiVersion: v1
kind: Service
metadata:
  labels:
    app: todolist
  name: todolist
spec:
  ports:
  - port: 3123
    protocol: TCP
    targetPort: 3123
  selector:
    app: todolist
  type: NodePort
