apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: log-blog
    tier: challenge
  name: log-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-blog
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
      labels:
        app: log-blog
        networkpolicy: allow_egress
        tier: challenge
    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image: gcr.io/bsides-sf-ctf-2022/log-blog:20220515-173433
        name: log-blog
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
          runAsNonRoot: true
      - env:
        - name: DEBUG
          value: 'true'
        - name: COOKIES
          value: admin=bf2b084a16d854065952ee3edba3e5e22391e0088cea348783b5f4f5208c35ec;URL=https://log-blog-15ba06e9.challenges.bsidessf.net/;httpOnly
        - name: PORT
          value: '3000'
        image: gcr.io/bsides-sf-ctf-2022/webbot:latest
        name: webbot
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 80m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes: []
