apiVersion: v1
kind: Service
metadata:
  labels:
    app: log-blog
  name: log-blog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: log-blog
  type: NodePort
