apiVersion: v1
kind: Service
metadata:
  labels:
    app: shurdles-1
  name: shurdles-1
spec:
  loadBalancerIP: 34.168.130.118
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: shurdles-1
  type: LoadBalancer
