apiVersion: v1
kind: Service
metadata:
  labels:
    app: pwncap
  name: pwncap
spec:
  loadBalancerIP: 35.203.191.84
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: pwncap
  type: LoadBalancer
