apiVersion: v1
kind: Service
metadata:
  labels:
    app: septoglyph
  name: septoglyph
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: septoglyph
  type: NodePort
